# Site settings
name: Less Or More
email: 303247612@qq.com
author: 郑诚
url: http://zhengchengyy.github.io
resume_site: https://zhengchengyy.github.io/blog
github: https://github.com/zhengchengyy
baseurl: /blog
description: Actually, less is more!
meta_description: 郑诚;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Boats against the current,borne forward!
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhengchengyy

# Build settings
markdown: kramdown

baidu_analysis: f088dc95206575a9202d91317c891b11

